# Basic mediawiki-node-services config, running the following services in a
# single process:
#
# - RESTBase
# - Parsoid

services:
  - name: restbase
    app_base_path: ./node_modules/restbase
    conf: 
      port: 7231
      salt: secret
      default_page_size: 125
      user_agent: RESTBase
      ui_name: RESTBase
      ui_url: https://www.mediawiki.org/wiki/RESTBase
      ui_title: RESTBase docs
      spec: 
        x-request-filters:
          - path: lib/security_response_header_filter.js
        x-sub-request-filters:
          - type: default
            name: http
            options:
            allow:
              - pattern: '{env(MEDIAWIKI_API_URL,http://localhost/w/api.php)}'
                forward_headers: true
              - pattern: http://localhost:8142
                forward_headers: true
              - pattern: /^https?:\/\//
        paths:
          /{domain:localhost}:
            x-modules:
              - path: projects/example.yaml
                options: &default_options
                  action:
                    # XXX Check API URL!
                    apiUriTemplate: '{env(MEDIAWIKI_API_URL,http://localhost/w/api.php)}'
                    baseUriTemplate: "{{'http://{domain}:7231/{domain}/v1'}}"
                  parsoid:
                    # XXX Check Parsoid URL!
                    host: http://localhost:8142
                  table:
                    backend: sqlite
                    dbname: /data/restbase_tables.sqlite3
                    pool_idle_timeout: 20000
                    retry_delay: 250
                    retry_limit: 10
                    show_sql: false
                  mathoid:
                    host: '{env(MATHOID_HOST_PORT,http://localhost:10044)}'
                  mobileapps:
                    host: '{env(MOBILEAPPS_URI,http://localhost:8888)}'
                  citoid:
                    host: '{env(CITOID_URI,http://localhost:1970)}'
                  purged_cache_control: s-maxage=864000, max-age=86400
          /{domain:wikimedia.org}:
            x-modules:
              - path: projects/wikimedia.org.yaml
                options: *default_options
  - name: parsoid
    entrypoint: apiServiceWorker
    conf:
      useSelser: true
      serverPort: 8142
      serverInterface: 0.0.0.0
      debug: false
      mwApis:
        - domain: localhost
          prefix: localhost
          uri: '{env(MEDIAWIKI_API_URL,http://localhost/w/api.php)}'
          strictSSL: '{env(STRICT_SSL,true)}'

# Finally, a standard service-runner config.
info:
  name: mediawiki-node-services

logging:
  level: info

num_workers: 1
